- examples/index.html
The ARIA IDL interface is fairly new and not yet implemented in Chrome & Firefox. https://w3c.github.io/aria/#idl-interface (does not exist in WAI-ARIA 1.1).
I believe the example page has never worked in Chrome due to this. This can be checked with `'role' in document.createElement('div')`, which is false in Chrome and Firefox, but true in Safari.
@koddsson can you run this locally to verify that it works for you with this change?
cc @haacked
> Fix example in Chrome

- README.md
Ref: https://github.com/github/text-expander-element/pull/3#issuecomment-513858403. This updates the README code with a more realistic example.
In the real world, instead of rendering the suggestions on the page and filtering on client side, people may `fetch('/emoji?q=' + text)` to get filtered suggestions from the server side. 
On github.com we first fetch, then memoize the fetch response, and then perform client side filtering.
The element code is extracted in this way so it does not dictate filtering and content generation logic. 
cc @haacked
> Update readme with a more realistic example and explain event.detail

- src/query.ts
- test/keyword-test.js
This regression was introduced in https://github.com/github/text-expander-element/pull/14 and only affects `multiword` mode. 
This PR fixes the issue and adds more tests to cover the code and protect from potential regressions.
> Prevent `multiword` mode from matching when there's a space immediately after activation key

- src/text-expander-element.ts
Related: https://github.com/github/issues/issues/1097
It seems the `event.stopImmediatePropagation()` prevents ESC keydown events from being triggered from a textarea within `text-expander-element` even when the menu is not present. 
This PR introduces a new condition to the initial `if` statement that check if the element's menu or combobox is present and returns if they are not, so that this eventlistener doesn't interfere with the propagation of the ESC key press when the menu is not activated.
> only stop the ESC keydown event propagation if menu or combobox present

- src/text-expander-element.ts
Related to: https://github.com/github/issues/issues/1097
Both the menu and combobox need to be set to null to deactivate them, otherwise there is always a combobox present after the first time the text-expander-element is triggered and will not register ESC keypresses anymore in the component after this element is activated.
**Update:**
I looked at the [combobox-nav package at the `destroy()` method](https://github.com/github/combobox-nav/blob/main/src/index.ts#L32), looks like it removed a bunch of attributes and removes eventlisteners. i still think it should be set to null so i moved that to end of `deactivate()` method.
> Set combobox to null when deactivate

- README.md
- examples/index.html
- src/query.ts
- src/text-expander-element.ts
- test/query-test.js
- test/text-expander-element-test.js
This PR adds the following behaviour to the `text-expander-element`:
If an activation key is specified in the `multiword` attribute, then its first occurrence should be treated as activating and the following occurrences should be ignored (treated as normal text).
For example, let's assume the `text-expander-element` is configured as :
```
<text-expander keys=": @ #" multiword="#">
<textarea></textarea>
</text-expander>
```
When the user types `#Implement #123`, the first `#` should be identified as the activation key and the following text `Implement #123` should be treated as the match i.e. `#123` should **NOT** create a new match. 
This gif shows the new behaviour.
> For multiword scenarios, ignore activation keys when a match is in progress.

- src/query.ts
- test/text-expander-element-test.js
Hullo,
I was trying to use `[[` as a key to trigger a multiword expander dropdown when I discovered that it behaved erratically, only occasionally firing my `provides` callback.
After digging into it and stepping through the tests, I deduced that when we reset the `keyIndex`, given a `lastMatchPosition`, we probably assumed keys were always of `length` 1. Once I set it to `key.length`, my test started to pass.
I'm not very experienced with modern js, so I wasn't sure how to structure the test and I'm happy to change it provided some guidance 😉.
Cheers,
> Fix support for multiWord queries with activations keys longer than than 1 character

- src/text-expander-element.ts
This pull request prevents the browser from scrolling to the bottom of a `textarea` when you click a selection from the suggestion list.
Here's an example based on [`./examples/index.html`](https://github.com/github/text-expander-element/blob/main/examples/index.html):
| Before | After |
|--------|--------|
| ![before](https://user-images.githubusercontent.com/2993937/146245177-e8d5bc18-8dde-429a-a943-77d9a34e1bd2.gif) | ![after](https://user-images.githubusercontent.com/2993937/146245200-a61d44ef-f286-4108-9265-e4cca3883182.gif) |
Thanks for taking a look! ✨
> fix: prevent scroll upon clicking selection from suggestion list

- src/text-expander-element.ts
- test/WrapperComponent.js
- test/text-expander-element-test.js
As mentioned in #24, when used inside a shadowRoot, the detection whether the input textarea is active, fails. This is because `document.activeElement` only returns the CustomElement but does not check inside its shadowRoot. This PR changes this by extending the check to also look inside the shadowRoot.
The provided test also adds a dummy CustomElement (`WrapperComponent`) to test usage inside a shadowRoot.
> Fix active element detection in shadow root

- README.md
- src/text-expander-element.ts
Adding a new event, `text-expander-committed`, that is dispatched after the underlying input's DOM value has been updated.
This is useful for allowing subscribing listeners to be able to handle when the DOM is updated. The particular use case this is solving is allowing us to sync up with React state when using `text-expander`.
cc @theinterned
> Add `text-expander-committed` event

- README.md
- src/text-expander-element.ts
Fixes: https://github.com/github/text-expander-element/issues/35
I was looking to add a test, but am not sure how. The current tests do not cover the `onCommit` function at all, the expansion mechanism is uncovered by tests it seems.
> Add `suffix` option to `<text-expander>`

- README.md
- src/text-expander-element.ts
- test/text-expander-element-test.js
In our case this was needed for a multi-step autofill, where first you select a type to insert, and then do the actual search.
e.g.:
```
#type:ID
```
> feat: allow continuation of expander menu

- .github/workflows/nodejs.yml
- README.md
- package-lock.json
- src/text-expander-element.ts
The intent here is to migrate the expander menus to use `[popover]`, as it solves some layout, z-index and overflow issues.
`top-layer` elements like `[popover]` and `dialog:modal` are laid out irrespective of offset or overflow parents, and so their position is always absolute to the window. In order for them to be correctly laid out we need to account for that, by putting them relative to the text area - which happens implicitly for non-top-layer elements.
In addition, in order to use `showPopover()` the element must be in the DOM, but we also need to ensure that it's open before we check to see if it's in the top-layer (a hidden popover is not in the top layer). Because the timing is very sensitive the only way to really do this is to make it observable as to when text-expander is …
> add toplayer support, plus active/deactivate events

- src/text-expander-element.ts
If a top-layer has position: absolute then window scrollX/Y should be accounted for.
> fix top-layer positioning absolute

- package-lock.json
- package.json
Updates `dom-input-range` to `1.1.6` to fix `DOMException` errors. The dependency was throwing exceptions when the custom element was registered a second time, which would happen on soft navigations. This was resolved in https://github.com/iansan5653/dom-input-range/pull/4
> Update `dom-input-range` to fix `DOMException` errors

- src/text-expander-element.ts
- test/text-expander-element-test.js
fixes https://github.com/github/text-expander-element/issues/62
Adds a keys setter so that react 19 can properly call set on the property.
React 19 does an `prop in Obj` check for whether to set properties or attributes, and since `keys` is found due to the getter it attempts to set that property on the javascript object instead of the attribute.  leading to an error since no setter is defined
this forwards the property setter to the attribute setter directly
> Add keys setter

- README.md
Was using the events API of the component, and noticed that one event was not working: it ended up being a typo in the docs.
> Fixes a typo in the README: dectivate → deactivate

- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
Update our runners to use `ubuntu-22.04` instead of `ubuntu-latest` since our karma dependencies that launch Chrome do not work on ubuntu-24
> ci: pin ubuntu runners to v22

- src/text-expander-element.ts
- Export existing types with `TextExpander` prefix. This is not breaking because previous unprefixed types were not being exported.
- Add and export type for `TextExpanderChangeEvent`
> Improve and export types

- src/index.ts
Followup to https://github.com/github/text-expander-element/pull/72.
I'm sorry I missed this. This makes it possible to import the types from `@github/text-expander-element` directly instead of having to import from `@github/text-expander-element/dist/text-expander-element.d.ts`.
The specific `export type *` syntax is supported since [Typescript 5.0](https://github.com/microsoft/TypeScript/pull/52217).
> Re-export the types in index.d.ts

- package-lock.json
- package.json
Upgrades the `dom-input-range` dependency to [version 2.x](https://github.com/iansan5653/dom-input-range/releases/tag/v2.0.0) so that we can use it elsewhere without multiple versions installed. There's no breaking changes since we're only using the `InputRange` API:
> There are no migration steps required for consumers using only the `InputRange` API.
> Upgrade dom-input-range to 2.0.0

- examples/index.html
- src/text-expander-element.ts
Possible fix #71 
---
Before (v2.9.2):
https://github.com/user-attachments/assets/f0134a25-fa25-469f-b0c5-0c014076d18c
After this PR:
https://github.com/user-attachments/assets/4070b133-046f-42cf-ad51-807c429e72ac
> fix match validation to prevent stale matches
